# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: round.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='round.proto',
  package='ai',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=b'\n\x0bround.proto\x12\x02\x61i\"\"\n\x04Tick\x12\r\n\x05robot\x18\x01 \x02(\t\x12\x0b\n\x03num\x18\x02 \x02(\x05\"\x1f\n\x05Round\x12\x16\n\x04tick\x18\x01 \x03(\x0b\x32\x08.ai.Tick'
)




_TICK = _descriptor.Descriptor(
  name='Tick',
  full_name='ai.Tick',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='robot', full_name='ai.Tick.robot', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='num', full_name='ai.Tick.num', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=19,
  serialized_end=53,
)


_ROUND = _descriptor.Descriptor(
  name='Round',
  full_name='ai.Round',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='tick', full_name='ai.Round.tick', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=55,
  serialized_end=86,
)

_ROUND.fields_by_name['tick'].message_type = _TICK
DESCRIPTOR.message_types_by_name['Tick'] = _TICK
DESCRIPTOR.message_types_by_name['Round'] = _ROUND
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Tick = _reflection.GeneratedProtocolMessageType('Tick', (_message.Message,), {
  'DESCRIPTOR' : _TICK,
  '__module__' : 'round_pb2'
  # @@protoc_insertion_point(class_scope:ai.Tick)
  })
_sym_db.RegisterMessage(Tick)

Round = _reflection.GeneratedProtocolMessageType('Round', (_message.Message,), {
  'DESCRIPTOR' : _ROUND,
  '__module__' : 'round_pb2'
  # @@protoc_insertion_point(class_scope:ai.Round)
  })
_sym_db.RegisterMessage(Round)


# @@protoc_insertion_point(module_scope)
